[package]
name = "habit-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
